### ISSUE TITLE
Spring is broken with bundler >= 1.11.0

### ISSUE THREAD

**Issue by ojab** [rails/spring#456] opened 2015-12-16 16:41 UTC
After https://github.com/bundler/bundler/pull/4002 (which is included into 1.11.0 and up) bundler restores RUBYLIB env var, but it seems that spring actually needs former behavior.
spring-1.6.0 (rails-4.2.5) w/ bundler >= 1.11.0 fails like this:
```
ojab-notebook:dashboard-ng ojab$ bundle exec rails c
/Users/ojab/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- bundler/setup (LoadError)
	from /Users/ojab/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/ojab/Documents/repos/phones/dashboard-ng/vendor/bundle/ruby/2.2.0/gems/spring-1.6.0/lib/spring/commands.rb:33:in `<module:Spring>'
	from /Users/ojab/Documents/repos/phones/dashboard-ng/vendor/bundle/ruby/2.2.0/gems/spring-1.6.0/lib/spring/commands.rb:4:in `<top (required)>'
	from /Users/ojab/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/ojab/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/ojab/Documents/repos/phones/dashboard-ng/vendor/bundle/ruby/2.2.0/gems/spring-1.6.0/lib/spring/application.rb:77:in `preload'
	from /Users/ojab/Documents/repos/phones/dashboard-ng/vendor/bundle/ruby/2.2.0/gems/spring-1.6.0/lib/spring/application.rb:143:in `serve'
	from /Users/ojab/Documents/repos/phones/dashboard-ng/vendor/bundle/ruby/2.2.0/gems/spring-1.6.0/lib/spring/application.rb:131:in `block in run'
	from /Users/ojab/Documents/repos/phones/dashboard-ng/vendor/bundle/ruby/2.2.0/gems/spring-1.6.0/lib/spring/application.rb:125:in `loop'
	from /Users/ojab/Documents/repos/phones/dashboard-ng/vendor/bundle/ruby/2.2.0/gems/spring-1.6.0/lib/spring/application.rb:125:in `run'
	from /Users/ojab/Documents/repos/phones/dashboard-ng/vendor/bundle/ruby/2.2.0/gems/spring-1.6.0/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Users/ojab/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/ojab/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```
sping app/server starts fine:
```
ojab            23200   0.1  0.1  2480972  11048   ??  Ss    4:38PM   0:00.12 spring app    | dashboard-ng | started 9 secs ago | development mode
ojab            23198   0.0  0.3  2505632  23612 s005  S     4:38PM   0:00.32 spring server | dashboard-ng | started 9 secs ago
```

Issue for bundler is filled (https://github.com/bundler/bundler/issues/4165), but I'm not really sure that it is their bug.

**Comment by ojab** [comment] 2015-12-16 16:45
…and looks like https://github.com/rails/spring/pull/453 fixes the issue.

**Comment by sonalkr132** [comment] 2015-12-17 04:25
Yes it does :grin: 
I added following to my gemfile:
```
gem 'spring', github: 'sonalkr132/spring', branch: 'bundler-dep'
```
and didn't get any error.

**Comment by jonleighton** [comment] 2015-12-24 12:00
#453 has been superseded by #458. However I don't really understand how it solves this issue? Can anyone explain what the issue was and why changing out gemfile solves it?

**Comment by ratracegrad** [comment] 2015-12-27 23:43
I am running into the error that I cannot generate a new controller/model/etc on my new installation of rails on my Mac because I am getting the errors:
rails g controller test1
/Users/jenniferbland/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- bundler/setup (LoadError)
	from /Users/jenniferbland/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/jenniferbland/Documents/projects/lynda/ruby4/Sites/simple_cms/vendor/bundle/gems/spring-1.6.1/lib/spring/commands.rb:33:in `<module:Spring>'
....
If I comment out the gem 'spring' line in my Gemfile everything works perfectly.

If I change the line to gem 'spring', github: 'sonalkr132/spring', branch: 'bundler-dep' as was mentioned above it installs spring and everything works perfectly.

So how do I get a new version of spring installed that will install and not generate the error message I am receiving when generating a new model/controller?

**Comment by morgoth** [comment] 2015-12-28 09:30
I also have this error on travis and confirm that https://github.com/rails/spring/pull/458 fixes it

**Comment by turboladen** [comment] 2015-12-29 00:31
I'm also getting the same error with ruby 2.3, rails 4.2.5, and spring 1.6.0 (or 1.6.1). I tried @sonalkr132 's solution: while I'm no longer getting the error, I'm also not getting the benefit of spring. For example, I `bin/rake spec` and see warnings and such that I get when the app is booting; I run the same again and see the same warnings. `bundle exec spring status` also shows `Spring is not running`.

**Comment by chrishough** [comment] 2016-01-08 02:47
@sonalkr132  I tried your version and it is still failing

**Comment by sonalkr132** [comment] 2016-01-08 03:30
@chrishough #458 isn't really a solution for it. It just so happens that it works some of the times.

#462 removes the line which is causing this error and it is pending review.

**Comment by chrishough** [comment] 2016-01-08 03:32
np @sonalkr132  -- I commented out spring for now to get around it.

**Comment by jonleighton** [comment] 2016-01-08 21:51
Does v1.6.2 (just released) solve this?

**Comment by turboladen** [comment] 2016-01-08 22:29
1.6.2 seems to get around crashes for me! I'm on chruby 0.3.9, ruby-install 0.6.0 (not sure if that matters), running ruby 2.3.0 and rails 4.2.5. Spring 1.6.0 and 1.6.1 were problematic for me.

Just one thing... I see `Running via Spring preloader in process [X]` when i `bin/rails c` or `bin/rake (anything)`, but nothing similar when i `bin/rails s`--is that expected? Boot time of `bin/rails s` is definitely consistently longer than the other commands, leading me to believe that sprint is not working for that command.

**Comment by jonleighton** [comment] 2016-01-09 08:30
Great, closing this then.

> Just one thing... I see Running via Spring preloader in process [X] when i bin/rails c or bin/rake (anything), but nothing similar when i bin/rails s--is that expected? Boot time of bin/rails s is definitely consistently longer than the other commands, leading me to believe that sprint is not working for that command.

Spring deliberately doesn't get involved in the `rails server` command. See https://github.com/rails/spring/pull/72.

**Comment by fschwan** [comment] 2016-01-10 18:41
1.6.2 does not fix Issue https://github.com/bundler/bundler/issues/4165 which might be a spring bug too.

**Comment by ojab** [comment] 2016-01-11 12:48
1.6.2 still crashes for me too, please reopen.

**Comment by jonleighton** [comment] 2016-01-11 12:55
Is the backtrace the same as before?

**Comment by ojab** [comment] 2016-01-11 13:39
yep, backtrace is the same.

**Comment by turboladen** [comment] 2016-01-11 19:26
@jonleighton :+1:

**Comment by sonalkr132** [comment] 2016-01-14 13:01
> bundler restores RUBYLIB env var, but it seems that spring actually needs former behavior.

This is the problem indeed.
In *bundler 1.10.6*, `$LOAD_PATH` looked like:
```
/home/user/testapp/vendor/bundle/ruby/2.2.0/gems/spring-1.6.2/lib
/home/user/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib    # Look for this line in next snippet
/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0
/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/x86_64-linux
/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby
/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/vendor_ruby/2.2.0
/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/vendor_ruby/2.2.0/x86_64-linux
/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/vendor_ruby
/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0
/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/x86_64-linux
```
and in *bundler 1.11.2*, `$LOAD_PATH` is:
```
/home/user/testapp/vendor/bundle/ruby/2.2.0/gems/spring-1.6.2/lib
/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0
/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/x86_64-linux
/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby
/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/vendor_ruby/2.2.0
/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/vendor_ruby/2.2.0/x86_64-linux
/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/vendor_ruby
/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0
/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/x86_64-linux
```
bundler line was in `ENV["RUBYLIB"]` but *bundler 1.11.0+* deletes it [here](https://github.com/bundler/bundler/pull/4002/files#diff-f51589bbb809dbcf630797a79ef32bedR283).

**Comment by sonalkr132** [comment] 2016-01-21 16:27
So, culprit is [this](https://github.com/rails/spring/blob/master/lib/spring/client/run.rb#L83) line:

```Ruby
paths  = Gem.path + ENV["GEM_PATH"].to_s.split(File::PATH_SEPARATOR)
```

Here, `ENV["GEM_PATH"]` is empty string. This is why both `GEM_PATH` and `GEM_HOME` has the same value:
```
/home/user/.rvm/gems/ruby-2.2.1
```
when former should be:
```
/home/user/.rvm/gems/ruby-2.2.1:/home/user/.rvm/gems/ruby-2.2.1@global
```

I checked `ENV.to_hash` and `ENV["_ORIGINAL_GEM_PATH"]` seems to have the required path, however I am not sure if I can use that. Suggestions?

cc: @jonleighton , @grosser

**Comment by notahat** [comment] 2016-01-27 01:31
I have some steps to reproduce the problem reliably.

The key line in here is `bundle install --path .bundle`. The error seems to occur as soon as you use a non-default bundle path. If you skip that line, the error doesn't occur.

```sh
$ bundle --version
Bundler version 1.11.2

$ rails --version
Rails 4.2.5.1

$ rails new foo
...
Bundle complete! 12 Gemfile dependencies, 54 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
         run  bundle exec spring binstub --all
* bin/rake: spring inserted
* bin/rails: spring inserted

$ cd foo
$ bundle install --path .bundle
...
Bundle complete! 12 Gemfile dependencies, 54 gems now installed.
Bundled gems are installed into ./.bundle.

$ spring --version
Spring version 1.6.2

$ bundle exec rails console
/Users/notahat/.rubies/ruby-2.2.4/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- bundler/setup (LoadError)
	from /Users/notahat/.rubies/ruby-2.2.4/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/notahat/Desktop/foo/.bundle/ruby/2.2.0/gems/spring-1.6.2/lib/spring/commands.rb:33:in `<module:Spring>'
	from /Users/notahat/Desktop/foo/.bundle/ruby/2.2.0/gems/spring-1.6.2/lib/spring/commands.rb:4:in `<top (required)>'
	from /Users/notahat/.rubies/ruby-2.2.4/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/notahat/.rubies/ruby-2.2.4/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/notahat/Desktop/foo/.bundle/ruby/2.2.0/gems/spring-1.6.2/lib/spring/application.rb:77:in `preload'
	from /Users/notahat/Desktop/foo/.bundle/ruby/2.2.0/gems/spring-1.6.2/lib/spring/application.rb:143:in `serve'
	from /Users/notahat/Desktop/foo/.bundle/ruby/2.2.0/gems/spring-1.6.2/lib/spring/application.rb:131:in `block in run'
	from /Users/notahat/Desktop/foo/.bundle/ruby/2.2.0/gems/spring-1.6.2/lib/spring/application.rb:125:in `loop'
	from /Users/notahat/Desktop/foo/.bundle/ruby/2.2.0/gems/spring-1.6.2/lib/spring/application.rb:125:in `run'
	from /Users/notahat/Desktop/foo/.bundle/ruby/2.2.0/gems/spring-1.6.2/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Users/notahat/.rubies/ruby-2.2.4/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/notahat/.rubies/ruby-2.2.4/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

**Comment by turboladen** [comment] 2016-01-27 21:41
> The error seems to occur as soon as you use a non-default bundle path.

That's not 100% true, @notahat. I use `vendor/bundle` for my bundle path and 1.6.2 fixed things for me. I do, however, run into the same problem you described when creating a new app.

**Comment by cknoxrun** [comment] 2016-01-29 04:03
Interesing, @turboladen, I also use `vendor/bundle` and 1.6.2 did not fix things for me. Here is my `.bundle/config`:

```yaml
---
BUNDLE_DISABLE_SHARED_GEMS: '1'
BUNDLE_PATH: vendor
```

I still get the same error as @notahat.

**Comment by jonleighton** [comment] 2016-01-30 19:44
Ok, I'm trying to wrap my head around what's going on here. Here are some notes, mainly for my own benefit:

* When Bundler loads, it needs to ensure that all child Ruby processes will operate "within" the bundle. Therefore it sets some environment variables that Ruby will use when it runs.
* Environment variables which it sets include:
  * `RUBYOPT`: which specifies command line options which should be automatically applied to the ruby process
  * `RUBYLIB`: which specifies paths which should be added to the `$LOAD_PATH` within the ruby process
* To ensure that child ruby processes operate within the bundle, bundler adds `-rbundler/setup` to `RUBYOPT`
* To ensure that `-rbundler/setup` works, the bundler source needs to be in the `$LOAD_PATH`. Bundler used to achieve this by also adding `-I[path]` to `RUBYOPT`, but that caused some problems with spaces in path names. Therefore in https://github.com/bundler/bundler/pull/2536 it switched to adding the path to `RUBYLIB`. This was released in Bundler version 1.5.0 (i.e. a long time ago).
* `Bundle.with_clean_env` is meant to clean the environment in order to "unload" bundler, so that you can launch child processes *without* them operating within the bundle.
* However, there was [a bug](https://github.com/bundler/bundler/issues/3982) where `Bundle.with_clean_env` did not properly clean the `RUBYLIB` environment variable. That was [fixed](https://github.com/bundler/bundler/pull/4002) and the fix was released in Bundler version 1.11 (i.e. quite recently)
* We use `Bundle.with_clean_env` [here](https://github.com/rails/spring/blob/c2c9fa3d4fc8ac8d9cb80dc5d8b670f54bd7f3a7/lib/spring/application_manager.rb#L95-L108), when launching the long-running Rails environments which spring uses to run commands. We do it [so that the Rails processes can be launched in a different Bundler environment than the Spring server process](https://github.com/rails/spring/commit/8b1a8d6e6c13e75f271af792f666660679e0742d) which enables Spring to restart your Rails processes even when the `Gemfile` changes.
* When we preload Rails inside the long-running Spring process, [we require `spring/commands`](https://github.com/rails/spring/blob/d20e5db73997d35c9180e8a51aea9482eae49d4f/lib/spring/application.rb#L77), which in turn [requires bundler](https://github.com/rails/spring/blob/d20e5db73997d35c9180e8a51aea9482eae49d4f/lib/spring/commands.rb#L33)
* Before Bundler 1.11, that worked because the `RUBYLIB` was guaranteed to contain the path to the bundler source, since `Bundle.with_clean_env` didn't remove it.
* After Bundle 1.11, there may now be cases where `RUBYLIB` doesn't contain the path to the bundler source, and therefore the require fails, as reported in this bug.
* Therefore we need to make sure we set `RUBYLIB` such that bundler can be found after calling `Bundle.with_clean_env`, since the "correct" behaviour of `Bundle.with_clean_env` is to remove bundler from that environment variable.

**Comment by turboladen** [comment] 2016-01-30 21:00
Just to follow up for @cknoxrun , here's a local `.bunde/config` for an app that's working for me:

```
---
BUNDLE_PATH: vendor/bundle
BUNDLE_DISABLE_SHARED_GEMS: '1'
BUNDLE_WITHOUT: production
```

And for giggles, some ENV vars with "ruby" in them, in case that's of any help:

```
twilight git:develop ❯ env | sift -i ruby
PATH=/Users/sloveless/.gem/ruby/2.3.0/bin:/Users/sloveless/.rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/bin:/Users/sloveless/.rubies/ruby-2.3.0/bin:/usr/local/heroku/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/texbin:/usr/local/heroku/bin:/usr/local/sbin:/Applications/Sublime Text.app/Contents/SharedSupport/bin:/Users/sloveless/Development/projects/config_files/tmux:/usr/local/share/npm/bin:/usr/local/opt/fzf/bin:/Applications/Sublime Text.app/Contents/SharedSupport/bin:/Users/sloveless/Development/projects/config_files/tmux:/usr/local/share/npm/bin
RUBY_ROOT=/Users/sloveless/.rubies/ruby-2.3.0
RUBYOPT=
RUBY_ENGINE=ruby
RUBY_VERSION=2.3.0
GEM_ROOT=/Users/sloveless/.rubies/ruby-2.3.0/lib/ruby/gems/2.3.0
GEM_HOME=/Users/sloveless/.gem/ruby/2.3.0
GEM_PATH=/Users/sloveless/.gem/ruby/2.3.0:/Users/sloveless/.rubies/ruby-2.3.0/lib/ruby/gems/2.3.0

```

Again, I'm using chruby and wonder if that plays into any variables here.

**Comment by jonleighton** [comment] 2016-01-30 21:11
Yes, I think it's highly likely your env is what shields you from this issue. (I'm trying to write a test and finding that the env needs to be just right in order to repro...)

**Closed** 2016-02-04 22:23 UTC

**Comment by jonleighton** [comment] 2016-02-04 22:25
After a drawn-out battle getting the CI to work, 1.6.3 is now out. It should fix this bug. Please try it.

**Comment by grosser** [comment] 2016-02-04 22:27
thx for your work on that, those are some nasty issues! :heart:

**Comment by cknoxrun** [comment] 2016-02-04 22:29
Thank you!! It works!

**Comment by turboladen** [comment] 2016-02-05 16:45
1.6.3 works for me (1.6.2 did too)!

**Comment by freswa** [comment] 2016-02-06 16:11
Thanks! Also works for me :+1:

**Comment by KazuyaHara** [comment] 2016-02-07 07:47
It works for me, too. Thanks!

**Comment by codeanpeace** [comment] 2016-02-08 15:33
Updating to 1.6.3 fixed it for me as well - thanks!

**Comment by fedemoretti** [comment] 2016-02-25 13:05
I'm running a new Rails project using `rails new foo`, with this gems versions:
Ruby: 2.3.0p7
Rails: 4.2.5.1
Bundler: 1.11.2
Spring: 1.6.3

But when I try to run `rails` command inside the project I get:
```
/Users/fefo/.rvm/rubies/ruby-2.3-head/lib/ruby/site_ruby/2.3.0/rubygems/path_support.rb:50:in `split_gem_path': undefined method `split' for #<Array:0x007fcb4aba5780> (NoMethodError)
	from /Users/fefo/.rvm/rubies/ruby-2.3-head/lib/ruby/site_ruby/2.3.0/rubygems/path_support.rb:32:in `initialize'
	from /Users/fefo/.rvm/rubies/ruby-2.3-head/lib/ruby/site_ruby/2.3.0/rubygems.rb:346:in `new'
	from /Users/fefo/.rvm/rubies/ruby-2.3-head/lib/ruby/site_ruby/2.3.0/rubygems.rb:346:in `paths='
	from /Users/fefo/Projects/web/foo/bin/spring:11:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'
```

I even get it trying to do `rails -v`

My `bin/spring` file looks like this:

```ruby
#!/usr/bin/env ruby

# This file loads spring without using Bundler, in order to be fast.
# It gets overwritten when you run the `spring binstub` command.

unless defined?(Spring)
  require 'rubygems'
  require 'bundler'

  if (match = Bundler.default_lockfile.read.match(/^GEM$.*?^    (?:  )*spring \((.*?)\)$.*?^$/m))
    Gem.paths = { 'GEM_PATH' => [Bundler.bundle_path.to_s, *Gem.path].uniq }
    gem 'spring', match[1]
    require 'spring/binstub'
  end
end
```

It's not the same error as described in this issue but I thought it might be related. In other case I can open a separate issue.

Any help would be appreciated,
Thanks,

**Comment by fedemoretti** [comment] 2016-02-25 13:20
I did a little bit of investigation and I found `Gem.path` has two paths:
```
/Users/fefo/.rvm/gems/ruby-2.3-head@rails4
/Users/fefo/.rvm/gems/ruby-2.3-head@global
```
It seems that I have GEM_PATH env variable set to:
```
/Users/fefo/.rvm/gems/ruby-2.3-head@rails4:/Users/fefo/.rvm/gems/ruby-2.3-head@global
```

Should I change this to have only one gemset? I actually don't know why I have both global and rails4 set.

**Comment by jhenahan** [comment] 2016-02-27 07:38
Hey, I hit this issue, too, and regenerating binstubs with

    bundle exec spring binstub --all

seems to have fixed it.

**Comment by MatayoshiMariano** [comment] 2016-07-13 13:15
Updating Rails binaries worked for me `bundle exec rake rails:update:bin`

**Comment by salomoko** [comment] 2017-03-19 03:07
@MatayoshiMariano your suggestion of running the `rails:update:bin` rake task saved the day for me as the main cause of my problem was I updated all my gems  and **rails (5.0.1)** updated to **rails (5.0.2)**. 

_Thought I'd share the root cause of my spring issues..._ 

If you're on rails 5.0.1 update all your gems via
`bundle update`
then run 
`be rake rails:update:bin`
and you'll be good! :)

**Comment by MatayoshiMariano** [comment] 2017-03-20 12:58
@salomoko I am glad that it worked!
